name: Venda_Online_Ui
description: Sistema Sibys da Direção dos Impostos de São Tomé e Principe.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cross_local_storage: ^1.1.1
  web_socket_channel: ^1.1.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  #TODO: VERDOCUMENTAÇAO
  velocity_x: ^0.4.1
  #TODO: VERDOCUMENTAÇAO
  flutter_neumorphic: ^3.0.1
  intl: ^0.16.1
  get: ^3.4.2
  responsive_framework: ^0.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
#  assets:
#    - files/

vars:
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner

scripts:
    build: $clean & $get & $runner build --delete-conflicting-outputs
    watch: $clean & $get & $runner watch --delete-conflicting-outputs
    w: $runner watch --delete-conflicting-outputs
